In [2]:
import pandas as pd 
import numpy as np
import warnings
warnings.filterwarnings(action='ignore')

In [9]:
df=pd.read_csv('/Users/shinmirim/Desktop/concrete.csv')

In [10]:
df.head()

,Cement,BlastFurnaceSlag,FlyAsh,Water,Superplasticizer,CoarseAggregate,FineAggregate,Age,CompressiveStrength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [17]:
df.drop(columns=['FlyAsh'],inplace=True)

In [18]:
df[['CoarseAggregate','FineAggregate']].sum()

CoarseAggregate    1002106.5
FineAggregate       796787.9
dtype: float64

In [19]:
df['AggregateSum']=df['CoarseAggregate']+df['FineAggregate']
df

,Cement,BlastFurnaceSlag,Water,Superplasticizer,CoarseAggregate,FineAggregate,Age,CompressiveStrength,AggregateSum
0,540.0,0.0,162.0,2.5,1040.0,676.0,28,79.99,1716.0
1,540.0,0.0,162.0,2.5,1055.0,676.0,28,61.89,1731.0
2,332.5,142.5,228.0,0.0,932.0,594.0,270,40.27,1526.0
3,332.5,142.5,228.0,0.0,932.0,594.0,365,41.05,1526.0
4,198.6,132.4,192.0,0.0,978.4,825.5,360,44.30,1803.9
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,179.6,8.9,870.1,768.3,28,44.28,1638.4
1026,322.2,0.0,196.0,10.4,817.9,813.4,28,31.18,1631.3
1027,148.5,139.4,192.7,6.1,892.4,780.0,28,23.70,1672.4
1028,159.1,186.7,175.6,11.3,989.6,788.9,28,32.77,1778.5
1029,260.9,100.5,200.6,8.6,864.5,761.5,28,32.40,1626.0

In [20]:
df

,Cement,BlastFurnaceSlag,Water,Superplasticizer,CoarseAggregate,FineAggregate,Age,CompressiveStrength,AggregateSum
0,540.0,0.0,162.0,2.5,1040.0,676.0,28,79.99,1716.0
1,540.0,0.0,162.0,2.5,1055.0,676.0,28,61.89,1731.0
2,332.5,142.5,228.0,0.0,932.0,594.0,270,40.27,1526.0
3,332.5,142.5,228.0,0.0,932.0,594.0,365,41.05,1526.0
4,198.6,132.4,192.0,0.0,978.4,825.5,360,44.30,1803.9
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,179.6,8.9,870.1,768.3,28,44.28,1638.4
1026,322.2,0.0,196.0,10.4,817.9,813.4,28,31.18,1631.3
1027,148.5,139.4,192.7,6.1,892.4,780.0,28,23.70,1672.4
1028,159.1,186.7,175.6,11.3,989.6,788.9,28,32.77,1778.5
1029,260.9,100.5,200.6,8.6,864.5,761.5,28,32.40,1626.0